# Site settings
title: Miguel Rentes
email: miguel.rentes@gmail.com
description: > 
  personal blog
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://rentes.github.io" # the base hostname & protocol for your site
twitter_username: rentes
github_username:  rentes

# Build settings
markdown: kramdown
