# Setup
title:               Clean Coding
header-img:          img/home-bg.jpg
email:               miguel.rentes@gmail.com
description:         "Miguel Rentes' personal blog about Software construction and related topics."
baseurl:             ""
url:                 "https://rentes.github.io"
twitter_username:    rentes
github_username:     rentes
facebook_username:   miguel.rentes
author:              Miguel Rentes

# Build settings
permalink:           pretty
relative_permalinks: true
markdown:            kramdown
highlighter:         pygments
paginate:            5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
