# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Miguel Rentes
tagline:          A blog on randomly chosen software topics.
url:              https://rentes.github.io
paginate:         1
baseurl:          /
author:
  name:           Miguel Rentes
  url:            https://twitter.com/rentes
  email:          miguel.rentes@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/rentes/
